CREATE TABLE IF NOT EXISTS Mangas (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(100) NOT NULL,
	stars INT NOT NULL DEFAULT 1 CHECK (stars >= 1 AND stars <= 5)
);